"""add_fsm_to_customer

Revision ID: a840a118dd1c
Revises: 0654b268321e
Create Date: 2026-06-15 23:43:05.337084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a840a118dd1c'
down_revision: Union[str, None] = '0654b268321e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('fsm_state', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('fsm_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'fsm_context')
    op.drop_column('customers', 'fsm_state')
    # ### end Alembic commands ###
